baseurl: /sunnyquang
brand:
  description: ''
  email: syiree.official@gmail.com
  mailchimp: {APIKey: 4ef6b1c6f1b1115a59cb247029d9e574-us16}
  name: Sunny Quang
  phone: '+17132568541'
  social: {facebook: 'https://www.facebook.com/sunny.quang.1', instagram: '', skype: sunnyquang,
    twitter: ''}
color: {primary: '#222222'}
data:
  about:
    paragraphs: ['Sunny is an experienced personal trainer and boxing instructor.
        His approach focuses on teaching functional exercises for anyone interested
        in improving mobility, sports performance, and weight loss.', 'Sunny began
        his personal training as an MMA fighter at the age of 19. He has several MMA
        fights under his belt and is currently being promoted by Legacy Fighting.
        In addition to being an accomplished MMA fighter, he has training across a
        wide spectrum of modalities including weightlifting, kettlebells, and boxing.
        His passion for training others is motivated by the conviction that we must
        counteract the inertia that accompanies our modern lifestyle by adopting a
        holistic mind body approach by utilizing functional exercises to develop mobility,
        power, and strength.', 'Sunny holds a degree from the National Personal Training
        Institute. His personal training certifications include NASM certified, Kettlebell
        certified, Trigger point certified, and as a Box n Burn boxing instructor.
        Sunny teaches boxing classes on the weekends. All levels are welcomed.']
  images:
    carousel:
    - {src: /sunnyquang/assets/img/carousel/3.jpg}
    - {src: /sunnyquang/assets/img/carousel/1.jpg}
    - {src: /sunnyquang/assets/img/carousel/2.jpg}
    certifications:
    - {src: /sunnyquang/assets/img/certifications/3.png}
    - {src: /sunnyquang/assets/img/certifications/1.png}
    - {src: /sunnyquang/assets/img/certifications/2.png}
  navbar:
    links:
    - {title: Home, url: /sunnyquang}
    - {title: About Me, url: /sunnyquang/about}
    - {title: Boxing, url: /sunnyquang/boxing}
    - {title: Training, url: /sunnyquang/training}
    - {title: Blog, url: /sunnyquang/#}
    - {title: Contact, url: /sunnyquang/contact.html}
  training:
    levels:
      advance:
        link: /sunnyquang/training/advance.html
        packages:
        - duration: 60
          equipment: [gym]
          image: {src: /sunnyquang/assets/img/training/thumbnails/1.jpg}
          name: Level 1
          price: 300
          sessions: 4
        - duration: 60
          equipment: [gym]
          image: {src: /sunnyquang/assets/img/training/thumbnails/2.jpg}
          name: Level 2
          price: 600
          sessions: 8
        - duration: 60
          equipment: [gym]
          image: {src: /sunnyquang/assets/img/training/thumbnails/3.jpg}
          name: Level 3
          price: 900
          sessions: 12
        tagline: Fitness beyond Limits
      beginner:
        link: /sunnyquang/training/beginner.html
        packages:
        - duration: 30
          equipment: [gym]
          image: {src: /sunnyquang/assets/img/training/thumbnails/1.jpg}
          name: Level 1
          price: 180
          sessions: 4
        - duration: 30
          equipment: [gym]
          image: {src: /sunnyquang/assets/img/training/thumbnails/2.jpg}
          name: Level 2
          price: 360
          sessions: 8
        - duration: 30
          equipment: [gym]
          image: {src: /sunnyquang/assets/img/training/thumbnails/3.jpg}
          name: Level 3
          price: 540
          sessions: 12
        tagline: Unlock your Potential
      intermediate:
        link: /sunnyquang/training/intermediate.html
        packages:
        - duration: 45
          equipment: [gym]
          image: {src: /sunnyquang/assets/img/training/thumbnails/1.jpg}
          name: Level 1
          price: 240
          sessions: 4
        - duration: 45
          equipment: [gym]
          image: {src: /sunnyquang/assets/img/training/thumbnails/2.jpg}
          name: Level 2
          price: 480
          sessions: 8
        - duration: 45
          image: {src: /sunnyquang/assets/img/training/thumbnails/3.jpg}
          name: Level 3
          price: 720
          sessions: 12
        tagline: Experience the Power of Transformation
description: ''
environment: development
exclude: [Gemfile, Gemfile.lock, package.json, node_modules, webpack.config.js, requirements,
  requirements.txt, build, Makefile, LICENSE, README.md, TODO.md]
gems: [jekyll-seo-tag]
lang: en
path: {assets: /home/achilles/dev/syiree/sunnyquang/assets, images: /home/achilles/dev/syiree/sunnyquang/assets/img,
  root: /home/achilles/dev/syiree/sunnyquang}
sass: {style: compressed}
twitter: {username: ''}
url: https://sunnyquang.com
urls: {assets: /sunnyquang/assets, data: /sunnyquang/assets/data, icons: /sunnyquang/assets/img/icons,
  images: /sunnyquang/assets/img}
